name: admin_side
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.4.4

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  gap: ^3.0.1
  get: ^4.6.6
  http: ^1.2.2
  intl: ^0.19.0
  responsive_framework: ^1.5.1
  syncfusion_flutter_datagrid: ^27.1.50

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/plantImages/
