name: admin_new
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  email_validator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  gap: ^3.0.1
  get: ^4.6.6
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  quickalert: ^1.1.0
  shared_preferences: ^2.3.2
  syncfusion_flutter_datagrid: ^27.1.51

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/images/
